-- ipeds_npsas_submit_ENRL
select ipeds_fsvn,
       ipeds_instid,
       ipeds_studyid,
       ipeds_studentid,
--            first_name,
--            middle_name,
--            last_name,
       first_enrl_month,
       first_enrl_day,
       first_enrl_year,
       last_enrl_month,
       last_enrl_day,
       last_enrl_year,
       degree_by_063020,
       has_xfer_hours,
       has_rem_dev_hours,
       is_first_time_stu,
       has_bach_degree,
       bach_rec_month,
       bach_rec_day,
       bach_rec_year,
       act_engl_score,
       act_math_score,
       act_read_score,
       act_sci_score,
       act_comp_score,
       sat_read_score,
       sat_math_score,
       sat_essay_score,
       program_ay1920,
       grad_degree_ay1920,
       class_level_ay1920,
       grad_month_ay1920,
       grad_day_ay1920,
       grad_year_ay1920,
       cum_gpa_ay1920,
       major1_ay1920,
       cip1_ay1920,
       major2_ay1920,
       cip2_ay1920,
       undeclared_ay1920,
       prgm_hrs_ay1920,
       hrs_clock_ay1920,
       hrs_credit_ay1920,
       cum_credits_ay1920,
       tuition_ay1920,
       tf_covid19_ay1920,
       rb_covid19_ay1920,
       residency_ay1920,
       enroll_summer_ptft_2019,
       enroll_summer_hrs_2019,
       enroll_fall_ptft_2019,
       enroll_fall_hrs_2019,
       enroll_spring_ptft_2020,
       enroll_spring_hrs_2020,
       enroll_summer_ptft_2020,
       enroll_summer_hrs_2020
from enroll.ipeds_npsas_sample_20;
